### ISSUE TITLE
Can't append to <Marker />

### ISSUE THREAD

**Issue by franciclo** [jgimbel/react-leaflet-div-icon#1]
Hello i'm making a custom marker using <DivIcon> but i also like to bind a popup to it like i would to a Marker, shoudn't i be able to append a DivIcon to a Marker as an icon? and bind a popup to that marker.
Now i'm using DivIcon alone, just to make the custom marker, and the popup separated, but i would like to use it all as a marker. 

```
var myIcon = L.divIcon({className: 'my-div-icon'});

L.marker([50.505, 30.57], {icon: myIcon}).addTo(map);
```

would be great to do something like

```
let myIcon = (
  <DivIcon>
    <div className='my-div-icon'>MyIcon</div>
  < DivIcon/>
)
<Marker
  position={position}
  icon={myIcon}>
  <Popup>
    <div>Simple popup</div>
  </Popup>
</Marker>
```

**Comment by jgimbel** [comment]
It would make sense. I believe because of how the children are rendered inside the div-icon, I will have to make a [context wrapper](http://stackoverflow.com/questions/38212174/is-it-possible-to-pass-context-into-a-component-instantiated-with-reactdom-rende). As a note this would only work with react-leaflet versions greater than 0.12.0

**Comment by franciclo** [comment]
ok, i don't get so much context, but anyway i'm making the markers and popups as html in divicon, and works pretty well this way, i wonder if it will work with markercluster plugin tho
Thanks

**Comment by steezeburger** [comment]
Hey all, just made a PR for this here: https://github.com/jgimbel/react-leaflet-div-icon/pull/5
